GET http://localhost:1234/notes

### obtener usuarios
GET http://localhost:3000/user/

### crear usuario
POST http://localhost:3000/user/create

Content-Type: application/json

{
    "name": "nombre",
    "email": "email",
    "telefono": 213131331
}

