GET http://localhost:1234/notes

### obtener usuarios
GET http://localhost:3000/user/

### crear usuario
POST http://localhost:3000/user/
Content-Type: application/json

{
    "name": "Pablo",
    "email": "Pedro@gmail.com",
    "telefono": 213131331
}

### Eliminar un usuario
DELETE http://localhost:3000/user/e342a171-6557-11ee-ad06-204ef64c69c6